### ISSUE TITLE
Migrate april posts from weebly to wordpress

### ISSUE THREAD

**Issue by sharonw** [isf-hack-night/project-tracker#24]
- [x] [http://www.indivisiblesf.org/2017-04-01-feinstein-spicer.html](http://www.indivisiblesf.org/2017-04-01-feinstein-spicer.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-becerra-emoluments.html](http://www.indivisiblesf.org/2017-04-02-becerra-emoluments.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-chiu-privacy.html](http://www.indivisiblesf.org/2017-04-02-chiu-privacy.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-kamala-harris-gorsuch.html](http://www.indivisiblesf.org/2017-04-02-kamala-harris-gorsuch.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-kamala-harris-russia.html](http://www.indivisiblesf.org/2017-04-02-kamala-harris-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-02-pelosi-budget.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-pelosi-russia.html](http://www.indivisiblesf.org/2017-04-02-pelosi-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-ting-privacy.html](http://www.indivisiblesf.org/2017-04-02-ting-privacy.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-weiner-privacy.html](http://www.indivisiblesf.org/2017-04-02-weiner-privacy.html)
- [x] [http://www.indivisiblesf.org/2017-04-02-weiner-sanctuary.html](http://www.indivisiblesf.org/2017-04-02-weiner-sanctuary.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-brown-healthy-california.html](http://www.indivisiblesf.org/2017-04-09-brown-healthy-california.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-feinstein-bannon.html](http://www.indivisiblesf.org/2017-04-09-feinstein-bannon.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-feinstein-russia.html](http://www.indivisiblesf.org/2017-04-09-feinstein-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-feinstein-syria.html](http://www.indivisiblesf.org/2017-04-09-feinstein-syria.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-kamala-harris-russia.html](http://www.indivisiblesf.org/2017-04-09-kamala-harris-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-kamala-harris-syria.html](http://www.indivisiblesf.org/2017-04-09-kamala-harris-syria.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-09-pelosi-budget.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-pelosi-syria.html](http://www.indivisiblesf.org/2017-04-09-pelosi-syria.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-speier-hiv.html](http://www.indivisiblesf.org/2017-04-09-speier-hiv.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-speier-syria.html](http://www.indivisiblesf.org/2017-04-09-speier-syria.html)
- [x] [http://www.indivisiblesf.org/2017-04-09-ting-bail.html](http://www.indivisiblesf.org/2017-04-09-ting-bail.html)
- [x] [http://www.indivisiblesf.org/2017-04-16-kamala-harris-budget.html](http://www.indivisiblesf.org/2017-04-16-kamala-harris-budget.html)
- [x] [http://www.indivisiblesf.org/2017-04-16-kamala-harris-escalation.html](http://www.indivisiblesf.org/2017-04-16-kamala-harris-escalation.html)
- [x] [http://www.indivisiblesf.org/2017-04-16-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-16-pelosi-budget.html)
- [x] [http://www.indivisiblesf.org/2017-04-16-pelosi-russia.html](http://www.indivisiblesf.org/2017-04-16-pelosi-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-16-pelosi-tax-returns.html](http://www.indivisiblesf.org/2017-04-16-pelosi-tax-returns.html)
- [x] [http://www.indivisiblesf.org/2017-04-16-speier-hatecrimes.html](http://www.indivisiblesf.org/2017-04-16-speier-hatecrimes.html)
- [x] [http://www.indivisiblesf.org/2017-04-16-speier-russia.html](http://www.indivisiblesf.org/2017-04-16-speier-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-19-feinstein-healthcare.html](http://www.indivisiblesf.org/2017-04-19-feinstein-healthcare.html)
- [x] [http://www.indivisiblesf.org/2017-04-19-feinstein-syria.html](http://www.indivisiblesf.org/2017-04-19-feinstein-syria.html)
- [x] [http://www.indivisiblesf.org/2017-04-19-feinstein-townhall-summary.html](http://www.indivisiblesf.org/2017-04-19-feinstein-townhall-summary.html)
- [x] [http://www.indivisiblesf.org/2017-04-19-feinstein-white-supremacy.html](http://www.indivisiblesf.org/2017-04-19-feinstein-white-supremacy.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-feinstein-healthcare.html](http://www.indivisiblesf.org/2017-04-23-feinstein-healthcare.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-feinstein-taxes.html](http://www.indivisiblesf.org/2017-04-23-feinstein-taxes.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-feinstein-townhall.html](http://www.indivisiblesf.org/2017-04-23-feinstein-townhall.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-kamala-harris-budget.html](http://www.indivisiblesf.org/2017-04-23-kamala-harris-budget.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-kamala-harris-daca.html](http://www.indivisiblesf.org/2017-04-23-kamala-harris-daca.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-23-pelosi-budget.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-pelosi-russia.html](http://www.indivisiblesf.org/2017-04-23-pelosi-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-pelosi-tax-returns.html](http://www.indivisiblesf.org/2017-04-23-pelosi-tax-returns.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-speier-fascists.html](http://www.indivisiblesf.org/2017-04-23-speier-fascists.html)
- [x] [http://www.indivisiblesf.org/2017-04-23-speier-healthcare.html](http://www.indivisiblesf.org/2017-04-23-speier-healthcare.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-feinstein-aca.html](http://www.indivisiblesf.org/2017-04-30-feinstein-aca.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-feinstein-russia.html](http://www.indivisiblesf.org/2017-04-30-feinstein-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-feinstein-white-supremacists.html](http://www.indivisiblesf.org/2017-04-30-feinstein-white-supremacists.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-kamala-harris-aca.html](http://www.indivisiblesf.org/2017-04-30-kamala-harris-aca.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-kamala-harris-russia.html](http://www.indivisiblesf.org/2017-04-30-kamala-harris-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-30-pelosi-budget.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-pelosi-north-korea.html](http://www.indivisiblesf.org/2017-04-30-pelosi-north-korea.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-speier-repro-rights.html](http://www.indivisiblesf.org/2017-04-30-speier-repro-rights.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-speier-russia.html](http://www.indivisiblesf.org/2017-04-30-speier-russia.html)
- [x] [http://www.indivisiblesf.org/2017-04-30-speier-wffa.html](http://www.indivisiblesf.org/2017-04-30-speier-wffa.html)

**Comment by sharonw** [comment]
Finished migrating the first 15 posts listed at http://www.indivisiblesf.org/sitemap.xml:

http://www.indivisiblesf.org/2017-04-01-feinstein-spicer.html
http://www.indivisiblesf.org/2017-04-02-becerra-emoluments.html
http://www.indivisiblesf.org/2017-04-02-kamala-harris-gorsuch.html
http://www.indivisiblesf.org/2017-04-09-brown-healthy-california.html
http://www.indivisiblesf.org/2017-04-09-feinstein-syria.html
http://www.indivisiblesf.org/2017-04-09-pelosi-syria.html
http://www.indivisiblesf.org/2017-04-09-ting-bail.html
http://www.indivisiblesf.org/2017-04-16-kamala-harris-budget.html
http://www.indivisiblesf.org/2017-04-16-kamala-harris-escalation.html
http://www.indivisiblesf.org/2017-04-16-pelosi-tax-returns.html
http://www.indivisiblesf.org/2017-04-16-speier-hatecrimes.html
http://www.indivisiblesf.org/2017-04-16-speier-russia.html
http://www.indivisiblesf.org/2017-04-19-feinstein-healthcare.html
http://www.indivisiblesf.org/2017-04-30-feinstein-russia.html
http://www.indivisiblesf.org/2017-04-30-speier-repro-rights.html

**Comment by 8gian** [comment]
- [ ] [http://www.indivisiblesf.org/2017-04-01-feinstein-spicer.html](http://www.indivisiblesf.org/2017-04-01-feinstein-spicer.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-becerra-emoluments.html](http://www.indivisiblesf.org/2017-04-02-becerra-emoluments.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-chiu-privacy.html](http://www.indivisiblesf.org/2017-04-02-chiu-privacy.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-kamala-harris-gorsuch.html](http://www.indivisiblesf.org/2017-04-02-kamala-harris-gorsuch.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-kamala-harris-russia.html](http://www.indivisiblesf.org/2017-04-02-kamala-harris-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-02-pelosi-budget.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-pelosi-russia.html](http://www.indivisiblesf.org/2017-04-02-pelosi-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-ting-privacy.html](http://www.indivisiblesf.org/2017-04-02-ting-privacy.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-weiner-privacy.html](http://www.indivisiblesf.org/2017-04-02-weiner-privacy.html)
- [ ] [http://www.indivisiblesf.org/2017-04-02-weiner-sanctuary.html](http://www.indivisiblesf.org/2017-04-02-weiner-sanctuary.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-brown-healthy-california.html](http://www.indivisiblesf.org/2017-04-09-brown-healthy-california.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-feinstein-bannon.html](http://www.indivisiblesf.org/2017-04-09-feinstein-bannon.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-feinstein-russia.html](http://www.indivisiblesf.org/2017-04-09-feinstein-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-feinstein-syria.html](http://www.indivisiblesf.org/2017-04-09-feinstein-syria.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-kamala-harris-russia.html](http://www.indivisiblesf.org/2017-04-09-kamala-harris-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-kamala-harris-syria.html](http://www.indivisiblesf.org/2017-04-09-kamala-harris-syria.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-09-pelosi-budget.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-pelosi-syria.html](http://www.indivisiblesf.org/2017-04-09-pelosi-syria.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-speier-hiv.html](http://www.indivisiblesf.org/2017-04-09-speier-hiv.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-speier-syria.html](http://www.indivisiblesf.org/2017-04-09-speier-syria.html)
- [ ] [http://www.indivisiblesf.org/2017-04-09-ting-bail.html](http://www.indivisiblesf.org/2017-04-09-ting-bail.html)
- [ ] [http://www.indivisiblesf.org/2017-04-16-kamala-harris-budget.html](http://www.indivisiblesf.org/2017-04-16-kamala-harris-budget.html)
- [ ] [http://www.indivisiblesf.org/2017-04-16-kamala-harris-escalation.html](http://www.indivisiblesf.org/2017-04-16-kamala-harris-escalation.html)
- [ ] [http://www.indivisiblesf.org/2017-04-16-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-16-pelosi-budget.html)
- [ ] [http://www.indivisiblesf.org/2017-04-16-pelosi-russia.html](http://www.indivisiblesf.org/2017-04-16-pelosi-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-16-pelosi-tax-returns.html](http://www.indivisiblesf.org/2017-04-16-pelosi-tax-returns.html)
- [ ] [http://www.indivisiblesf.org/2017-04-16-speier-hatecrimes.html](http://www.indivisiblesf.org/2017-04-16-speier-hatecrimes.html)
- [ ] [http://www.indivisiblesf.org/2017-04-16-speier-russia.html](http://www.indivisiblesf.org/2017-04-16-speier-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-19-feinstein-healthcare.html](http://www.indivisiblesf.org/2017-04-19-feinstein-healthcare.html)
- [ ] [http://www.indivisiblesf.org/2017-04-19-feinstein-syria.html](http://www.indivisiblesf.org/2017-04-19-feinstein-syria.html)
- [ ] [http://www.indivisiblesf.org/2017-04-19-feinstein-townhall-summary.html](http://www.indivisiblesf.org/2017-04-19-feinstein-townhall-summary.html)
- [ ] [http://www.indivisiblesf.org/2017-04-19-feinstein-white-supremacy.html](http://www.indivisiblesf.org/2017-04-19-feinstein-white-supremacy.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-feinstein-healthcare.html](http://www.indivisiblesf.org/2017-04-23-feinstein-healthcare.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-feinstein-taxes.html](http://www.indivisiblesf.org/2017-04-23-feinstein-taxes.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-feinstein-townhall.html](http://www.indivisiblesf.org/2017-04-23-feinstein-townhall.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-kamala-harris-budget.html](http://www.indivisiblesf.org/2017-04-23-kamala-harris-budget.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-kamala-harris-daca.html](http://www.indivisiblesf.org/2017-04-23-kamala-harris-daca.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-23-pelosi-budget.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-pelosi-russia.html](http://www.indivisiblesf.org/2017-04-23-pelosi-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-pelosi-tax-returns.html](http://www.indivisiblesf.org/2017-04-23-pelosi-tax-returns.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-speier-fascists.html](http://www.indivisiblesf.org/2017-04-23-speier-fascists.html)
- [ ] [http://www.indivisiblesf.org/2017-04-23-speier-healthcare.html](http://www.indivisiblesf.org/2017-04-23-speier-healthcare.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-feinstein-aca.html](http://www.indivisiblesf.org/2017-04-30-feinstein-aca.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-feinstein-russia.html](http://www.indivisiblesf.org/2017-04-30-feinstein-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-feinstein-white-supremacists.html](http://www.indivisiblesf.org/2017-04-30-feinstein-white-supremacists.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-kamala-harris-aca.html](http://www.indivisiblesf.org/2017-04-30-kamala-harris-aca.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-kamala-harris-russia.html](http://www.indivisiblesf.org/2017-04-30-kamala-harris-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-pelosi-budget.html](http://www.indivisiblesf.org/2017-04-30-pelosi-budget.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-pelosi-north-korea.html](http://www.indivisiblesf.org/2017-04-30-pelosi-north-korea.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-speier-repro-rights.html](http://www.indivisiblesf.org/2017-04-30-speier-repro-rights.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-speier-russia.html](http://www.indivisiblesf.org/2017-04-30-speier-russia.html)
- [ ] [http://www.indivisiblesf.org/2017-04-30-speier-wffa.html](http://www.indivisiblesf.org/2017-04-30-speier-wffa.html)

**Comment by sharonw** [comment]
I added http://www.indivisiblesf.org/2017-04-19-feinstein-townhall-summary.html to both Actions and News when I migrated it to a Wordpress post because unlike the typical call script, it reports on a noteworthy event.
