### ISSUE TITLE
Migrate all posts from July from weebly to wordpress site

### ISSUE THREAD

**Issue by 8gian** [isf-hack-night/project-tracker#32]
- [x] [http://www.indivisiblesf.org/2017-07-02-deleon-isp-privacy.html](http://www.indivisiblesf.org/2017-07-02-deleon-isp-privacy.html)
- [x] [http://www.indivisiblesf.org/2017-07-02-feinstein-trumpcare.html](http://www.indivisiblesf.org/2017-07-02-feinstein-trumpcare.html)
- [x] [http://www.indivisiblesf.org/2017-07-02-kamala-harris-townhall.html](http://www.indivisiblesf.org/2017-07-02-kamala-harris-townhall.html)
- [x] [http://www.indivisiblesf.org/2017-07-02-kamala-harris-trumpcare.html](http://www.indivisiblesf.org/2017-07-02-kamala-harris-trumpcare.html)
- [x] [http://www.indivisiblesf.org/2017-07-02-pelosi-healthcare.html](http://www.indivisiblesf.org/2017-07-02-pelosi-healthcare.html)
- [x] [http://www.indivisiblesf.org/2017-07-02-speier-hr620.html](http://www.indivisiblesf.org/2017-07-02-speier-hr620.html)
- [x] [http://www.indivisiblesf.org/2017-07-02-speier-kateslaw.html](http://www.indivisiblesf.org/2017-07-02-speier-kateslaw.html)
- [x] [http://www.indivisiblesf.org/2017-07-02-speier-military-delays.html](http://www.indivisiblesf.org/2017-07-02-speier-military-delays.html)
- [x] [http://www.indivisiblesf.org/2017-07-05-ting-cap-trade.html](http://www.indivisiblesf.org/2017-07-05-ting-cap-trade.html)
- [x] [http://www.indivisiblesf.org/2017-07-09-feinstein-town-hall.html](http://www.indivisiblesf.org/2017-07-09-feinstein-town-hall.html)
- [x] [http://www.indivisiblesf.org/2017-07-09-feinstein-voter-access-305534-445823.html](http://www.indivisiblesf.org/2017-07-09-feinstein-voter-access-305534-445823.html)
- [x] [http://www.indivisiblesf.org/2017-07-09-feinstein-voter-access.html](http://www.indivisiblesf.org/2017-07-09-feinstein-voter-access.html)
- [x] [http://www.indivisiblesf.org/2017-07-11-chiu-cap-trade-476965-696805.html](http://www.indivisiblesf.org/2017-07-11-chiu-cap-trade-476965-696805.html)
- [x] [http://www.indivisiblesf.org/2017-07-11-ting-cap-trade-476965.html](http://www.indivisiblesf.org/2017-07-11-ting-cap-trade-476965.html)
- [x] [http://www.indivisiblesf.org/2017-07-11-weiner-cap-trade.html](http://www.indivisiblesf.org/2017-07-11-weiner-cap-trade.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-draft-impeachment-resolution.html](http://www.indivisiblesf.org/2017-07-16-draft-impeachment-resolution.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-feinstein-aumf.html](http://www.indivisiblesf.org/2017-07-16-feinstein-aumf.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-feinstein-trumpcare.html](http://www.indivisiblesf.org/2017-07-16-feinstein-trumpcare.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-feinstein-voting-rights.html](http://www.indivisiblesf.org/2017-07-16-feinstein-voting-rights.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-kamala-harris-trumpcare-333945.html](http://www.indivisiblesf.org/2017-07-16-kamala-harris-trumpcare-333945.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-kamala-harris-trumpcare.html](http://www.indivisiblesf.org/2017-07-16-kamala-harris-trumpcare.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-pelosi-russia-environment.html](http://www.indivisiblesf.org/2017-07-16-pelosi-russia-environment.html)
- [x] [http://www.indivisiblesf.org/2017-07-16-sf-sup-peskin.html](http://www.indivisiblesf.org/2017-07-16-sf-sup-peskin.html)

**Comment by girlgeek** [comment]
Fri Eve:  All posts moved.  Need to check on title color & url.  I set & some seem to get lost.
