### ISSUE TITLE
http://www.indivisiblesf.org/harris-muslim-ban-1-30.html

### ISSUE THREAD

**Issue by sharonw** [isf-hack-night/project-tracker#7]

**Comment by 8gian** [comment]
Original Page: [http://www.indivisiblesf.org/harris-muslim-ban-1-30.html](http://www.indivisiblesf.org/harris-muslim-ban-1-30.html)

**Comment by 8gian** [comment]
This issue should actually be added as a backdated post.

**Comment by 8gian** [comment]
New page: [http://isf.irobert.org/2017/01/phone-script-for…n-the-muslim-ban](http://isf.irobert.org/2017/01/phone-script-for…n-the-muslim-ban)
